export {default as Home } from './Home'
export {default as Aboutme } from './Aboutme'
export {default as Resume } from './Resume'
export {default as Blog } from './Blog'
export {default as Testimonials } from './Testimonials'
export {default as Contact } from './Contact'